### ISSUE TITLE
Win10 x64 UI button images not showing

### ISSUE THREAD

**Issue by RandyHaylor** [DougRogers/Tinta#2]
![image](https://user-images.githubusercontent.com/31674848/197252961-5e832d19-f068-4451-8672-90e0151f9748.png)

**Comment by RandyHaylor** [comment]
It was always like this - I didn't realize there were functional buttons there until I tried to look for the submit bug icon.

**Comment by DougRogers** [comment]
Those are in a sub folder and should be displayed.  Investigating.

**Comment by RandyHaylor** [comment]
![image](https://user-images.githubusercontent.com/31674848/197257410-db401676-c1f5-4983-82a4-e7e389d5d93a.png)
The icons are there, but the folder structure looks odd

**Comment by DougRogers** [comment]
That is odd.  It looks like Microsoft is changing the name of the install location.  Is Tinta.exe in the Tinta folder?

**Comment by RandyHaylor** [comment]
Yes, I found the folder by right clicking on the tinta exe in task manger
    On Friday, October 21, 2022 at 02:19:38 PM EDT, DougRogers ***@***.***> wrote:  
 
 


That is odd. It looks like Microsoft is changing the name of the install location. Is Tinta.exe in the Tinta folder?

**Comment by DougRogers** [comment]
Fixed in 0.9.40

**Comment by RandyHaylor** [comment]
Confirmed fixed on same system initial issue occurred on.
    On Monday, October 24, 2022 at 10:47:39 AM EDT, DougRogers ***@***.***> wrote:  
 
 


Fixed in 0.9.40
