### ISSUE TITLE
Crashed 3 times after selecting drive during a large move

### ISSUE THREAD

**Issue by RandyHaylor** [DougRogers/Tinta#3]
![image](https://user-images.githubusercontent.com/31674848/197256626-24d17a3b-806b-4e1b-899f-5fe66930b199.png)

I was moving a large folder from ssd to hdd, opened tinta and selected ssd (which should have been able to handle both requests while copying).

The third time it opened, it might be possible that it's timing out too soon on a response from the file system.

**Comment by DougRogers** [comment]
Did you upload the crash data?

**Comment by RandyHaylor** [comment]
I clicked yes when it asked to send the data. Didn't get any feedback when it closed, so unsure if it went or not.
    On Friday, October 21, 2022 at 04:37:00 PM EDT, DougRogers ***@***.***> wrote:  
 
 


Did you upload the crash data?

**Comment by DougRogers** [comment]
It was sent correctly, but it is not giving me the proper stack trace.  I will send you a private build to try to see if I can get a meaningful crash dump

**Comment by RandyHaylor** [comment]
Sounds good. Last couple times it opened OK, but I'll try to recreate the situation with stuff being copied between drives while I open 


Sent from Yahoo Mail for iPhone


On Friday, October 21, 2022, 5:19 PM, DougRogers ***@***.***> wrote:




It was sent correctly, but it is not giving me the proper stack trace. I will send you a private build to try to see if I can get a meaningful crash dump

**Comment by DougRogers** [comment]
Please try to repro this with 0.9.40 and upload the crash data.

**Comment by RandyHaylor** [comment]
Only crashed once on the 3rd of 10 attempts to open under same conditions.  Sent the crash report when prompted.




    On Monday, October 24, 2022 at 10:49:12 AM EDT, DougRogers ***@***.***> wrote:  
 
 


Please try to repro this with 0.9.40 and upload the crash data.

**Comment by DougRogers** [comment]
I was able to use the crash dump file and see where the issue is.  Thanks for testing and sending the report.  Unfortunately, the issue is with Microsoft's concurrent_unordered_set.  I will add a workaround.

**Comment by RandyHaylor** [comment]
Glad you were able to figure it out. I'm curious about what was happening & what the workaround was
    On Monday, October 24, 2022 at 12:41:46 PM EDT, DougRogers ***@***.***> wrote:  
 
 


I was able to use the crash dump file and see where the issue is. Thanks for testing and sending the report. Unfortunately, the issue is with Microsoft's concurrent_unordered_set. I will add a workaround.

**Comment by DougRogers** [comment]
It seems that parallel threads making copies of a concurrent_unordered_set can crash.  
I put a mutex around the access to avoid the copies from happening in parallel and avoided the copy.

So instead of a copy, I locked the set and gave access to it, then unlocked it afterwards.

**Comment by RandyHaylor** [comment]
Interesting, good fix!
    On Monday, October 24, 2022 at 05:03:12 PM EDT, DougRogers ***@***.***> wrote:  
 
 


It seems that parallel threads making copies of a concurrent_unordered_set can crash.
I put a mutex around the access to avoid the copies from happening in parallel.

**Comment by DougRogers** [comment]
Please retry with 0.9.41.  Posted this morning.

**Comment by RandyHaylor** [comment]
Tested - Could not repeat initial issue exactly, but a couple other things happened:
 - First open after updating failed silently after selecting C:\ ssd as source (was not copying in background yet, but my Unity 3d editor had hung on re-importing assets - a common bug, so who knows what was going on with my system at that point, could probably ignore this as a fluke...)
 - Started copying large collection of files from c: ssd to hdd as previously       - Opened Tinta 10 times - leaving default settings on c: for seletion, not clicking full scan.             - The only error I got was that on the 4th try, closing the app hung on indexing files after close, had to end task to close. Only thing that was visible was the indexing progress bar window - bar was full


fyi - it asks for permissions every time I open the app, and it asks for drive selection every time. Unsure if this is by design for development or not, thought I'd mention it.


    On Wednesday, October 26, 2022 at 11:57:48 AM EDT, DougRogers ***@***.***> wrote:  
 
 


Please retry with 0.9.41. Posted this morning.

**Comment by DougRogers** [comment]
Please file these as separate issues  Thanks.

"First open after updating failed silently"  I filed that here  #4

**Comment by DougRogers** [comment]
If you believe this issue has been resolved, please close.  It can be reopened if needed.

**Comment by RandyHaylor** [comment]
Couldn't reproduce, and the issue from the crash dump was addressed - closing.
