### ISSUE TITLE
Crashes once at start up after install

### ISSUE THREAD

**Issue by DougRogers** [DougRogers/Tinta#4]
Tinta silently exits after first install, but not after that.

**Comment by RandyHaylor** [comment]
After I updated on 10/26 via the ms app store & opened from within the app store, I selected c:\ and hit apply, then the app crashed silently and was closed.

**Comment by DougRogers** [comment]
@RandyHaylor Please retry with 0.9.42

**Comment by RandyHaylor** [comment]
(first run after the update did not crash, but had a weird experience in the ms store)
 - Opened MS Store - only option was 'Install' (not Open/Update like before) - Clicked install & it hung, came back 20 minutes later, same state:


 - Closed MS Store window & re-opened, then saw normal Open/Update buttons... - Applied update normally, and the first run after the update did not crash.






    On Thursday, October 27, 2022 at 09:25:00 AM EDT, DougRogers ***@***.***> wrote:  
 
 


@RandyHaylor Please retry with 0.9.42

**Comment by DougRogers** [comment]
That is odd behavior for the MS store.  It may be because the app was updated.

I am closing this issue. Please reopen if you observe this crash again.

**Comment by RandyHaylor** [comment]
Sounds good!
    On Thursday, October 27, 2022 at 01:08:16 PM EDT, DougRogers ***@***.***> wrote:  
 
 


That is odd behavior for the MS store. It may be because the app was updated.

I am closing this issue. Please reopen if you observe this crash again.
