### ISSUE TITLE
App Hangs on Indexing Window After Close

### ISSUE THREAD

**Issue by RandyHaylor** [DougRogers/Tinta#5]
(happened while testing separate crash issue while opening while a large ssd-> hdd xfer was running in the background)
- Started copying large collection of files from c: ssd to hdd as previously
       - Opened Tinta 10 times - leaving default settings on c: for seletion, not clicking full scan.
             - The only error I got was that on the 4th try, closing the app hung on indexing files after close, had to end task to close. Only thing that was visible was the indexing progress bar window - bar was full

**Comment by DougRogers** [comment]
Does not occur in current build
